# Generated by Django 5.0.6 on 2024-06-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rooms',
        ),
    ]
