# Generated by Django 5.0.6 on 2024-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rooms',
            field=models.ManyToManyField(related_name='messages', to='main.room'),
        ),
    ]
