# Generated by Django 5.0.6 on 2024-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='main.message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='members', to='main.room'),
        ),
    ]
