# Generated by Django 5.0.6 on 2024-06-29 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_message_rooms_room_messages_alter_user_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='users_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='rooms_set', to='main.message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='members_set', to='main.room'),
        ),
    ]
